version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online-articles-db
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#23
    volumes:
      - minio-data:/data

volumes:
  minio-data:   # Define the minio-data volume here
  postgres_data: # Define the postgres_data volume here
